name: deployment
# 触发条件
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch: # 允许手动运行，便于调试
# 任务
jobs:
  deploy:
    # 运行的环境
    runs-on: ubuntu-latest
    # 限制主仓库运行
    if: github.repository == 'BUAA-Software-Engineering-2023/Hospital-Frontend'
    # 步骤
    steps:
      - uses: actions/checkout@v2 # git pull
      - name: 登录服务器, 执行脚本
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: whoami
