name: deployment
# 触发条件
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch: # 允许手动运行，便于调试

# 任务
jobs:
  deploy:
    # 运行的环境
    runs-on: ubuntu-latest
    # 限制主仓库运行
    if: github.repository == 'BUAA-Software-Engineering-2023/Hospital-Frontend'
    # 步骤
    steps:
      - name: 配置ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
      - name: 测试
        run: ssh staging 'whoami'
